// ****************** ExceptionGeneratorDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorDuts__h_INCLUDED
#define _ExceptionGeneratorDuts__h_INCLUDED
#include "ExceptionGeneratorServices.h"

#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
} ST_FB_ExceptionGenerator_FB_init, *PST_FB_ExceptionGenerator_FB_init;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[6];
} ST_FB_ExceptionGenerator_FB_init, *PST_FB_ExceptionGenerator_FB_init;
#endif

typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit
{
	PVOID pInst;
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit;

#if defined(_X86_)
typedef struct _ST_GetSet_E_FpExcptCtrlSet
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_GetSet_E_FpExcptCtrlSet, *PST_GetSet_E_FpExcptCtrlSet;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_FpExcptCtrlSet
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_GetSet_E_FpExcptCtrlSet, *PST_GetSet_E_FpExcptCtrlSet;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_E_StepSizeAdaptation
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
} ST_GetSet_E_StepSizeAdaptation, *PST_GetSet_E_StepSizeAdaptation;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_StepSizeAdaptation
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_StepSizeAdaptation, *PST_GetSet_E_StepSizeAdaptation;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_UINT
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[2];
} ST_GetSet_UINT, *PST_GetSet_UINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_UINT
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[6];
} ST_GetSet_UINT, *PST_GetSet_UINT;
#endif

#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	unsigned char reserved1[3];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	unsigned char reserved1[7];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit;
#endif

typedef struct _ST_GetSet_ITcADI
{
	PVOID pInst;
	ITcADI* ipParam;
} ST_GetSet_ITcADI, *PST_GetSet_ITcADI;

#if defined(_X86_)
typedef struct _ST_GetSet_TcTraceLevel
{
	PVOID pInst;
	TcTraceLevel eParam;
} ST_GetSet_TcTraceLevel, *PST_GetSet_TcTraceLevel;
#elif defined(_X64_)
typedef struct _ST_GetSet_TcTraceLevel
{
	PVOID pInst;
	TcTraceLevel eParam;
	unsigned char reserved1[4];
} ST_GetSet_TcTraceLevel, *PST_GetSet_TcTraceLevel;
#endif

typedef struct _ST_FB_ExceptionGenerator_FB_Main
{
	PVOID pInst;
} ST_FB_ExceptionGenerator_FB_Main, *PST_FB_ExceptionGenerator_FB_Main;

#if defined(_X86_)
typedef struct _ST_GetSet_HRESULT
{
	PVOID pInst;
	HRESULT nParam;
} ST_GetSet_HRESULT, *PST_GetSet_HRESULT;
#elif defined(_X64_)
typedef struct _ST_GetSet_HRESULT
{
	PVOID pInst;
	HRESULT nParam;
	unsigned char reserved1[4];
} ST_GetSet_HRESULT, *PST_GetSet_HRESULT;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_TCOM_STATE
{
	PVOID pInst;
	TCOM_STATE eParam;
} ST_GetSet_TCOM_STATE, *PST_GetSet_TCOM_STATE;
#elif defined(_X64_)
typedef struct _ST_GetSet_TCOM_STATE
{
	PVOID pInst;
	TCOM_STATE eParam;
	unsigned char reserved1[4];
} ST_GetSet_TCOM_STATE, *PST_GetSet_TCOM_STATE;
#endif

typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main
{
	PVOID pInst;
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main;

#if defined(_X86_)
typedef struct _ST_GetSet_ST_ExceptionInfo
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
} ST_GetSet_ST_ExceptionInfo, *PST_GetSet_ST_ExceptionInfo;
#elif defined(_X64_)
typedef struct _ST_GetSet_ST_ExceptionInfo
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
	unsigned char reserved1[4];
} ST_GetSet_ST_ExceptionInfo, *PST_GetSet_ST_ExceptionInfo;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_E_ExecutionSequence1
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
} ST_GetSet_E_ExecutionSequence1, *PST_GetSet_E_ExecutionSequence1;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_ExecutionSequence1
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_ExecutionSequence1, *PST_GetSet_E_ExecutionSequence1;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_OTCID
{
	PVOID pInst;
	OTCID nParam;
} ST_GetSet_OTCID, *PST_GetSet_OTCID;
#elif defined(_X64_)
typedef struct _ST_GetSet_OTCID
{
	PVOID pInst;
	OTCID nParam;
	unsigned char reserved1[4];
} ST_GetSet_OTCID, *PST_GetSet_OTCID;
#endif

#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	unsigned char reserved1[3];
} ST_FB_ExceptionGenerator_FB_exit, *PST_FB_ExceptionGenerator_FB_exit;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	unsigned char reserved1[7];
} ST_FB_ExceptionGenerator_FB_exit, *PST_FB_ExceptionGenerator_FB_exit;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_E_CallerVerification
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
} ST_GetSet_E_CallerVerification, *PST_GetSet_E_CallerVerification;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_CallerVerification
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_CallerVerification, *PST_GetSet_E_CallerVerification;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_ULINT
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG nParam;
} ST_GetSet_ULINT, *PST_GetSet_ULINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_ULINT
{
	PVOID pInst;
	ULONGLONG nParam;
} ST_GetSet_ULINT, *PST_GetSet_ULINT;
#endif

typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct
{
	TCOM_STATE eObjState;
	OTCID nOid;
	OTCID nTaskOid;
	ULONG nTaskSortOrder;
	TcTraceLevel eTraceLevelMax;
	TcMgSdk::ModuleCaller eModuleCaller;
	TcMgSdk::CallerVerification eCallerVerification;
	TcMgSdk::StepSizeAdaptation eStepSizeAdaptation;
	TcMgSdk::ExecutionSequence1 eExecutionSequence;
	bool bExecute;
	unsigned char reserved1[3];
	TCOM_STATE eAccessLockState;
	TcMgSdk::FpExcptCtrlSet eInitExceptionHandling;
	TcMgSdk::FpExcptCtrlSet eUpdateExceptionHandling;
	unsigned char reserved2[2];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stInit;
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stInit;
	unsigned char reserved2[4];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_ST_ModuleBuildInfo
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
} ST_GetSet_ST_ModuleBuildInfo, *PST_GetSet_ST_ModuleBuildInfo;
#elif defined(_X64_)
typedef struct _ST_GetSet_ST_ModuleBuildInfo
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
	unsigned char reserved1[4];
} ST_GetSet_ST_ModuleBuildInfo, *PST_GetSet_ST_ModuleBuildInfo;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_UDINT
{
	PVOID pInst;
	ULONG nParam;
} ST_GetSet_UDINT, *PST_GetSet_UDINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_UDINT
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_GetSet_UDINT, *PST_GetSet_UDINT;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_E_ModuleCaller
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
} ST_GetSet_E_ModuleCaller, *PST_GetSet_E_ModuleCaller;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_ModuleCaller
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_ModuleCaller, *PST_GetSet_E_ModuleCaller;
#endif

#if defined(_X86_)
typedef struct _ST_GetSet_E_FpExcptCtrlSetEx
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_GetSet_E_FpExcptCtrlSetEx, *PST_GetSet_E_FpExcptCtrlSetEx;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_FpExcptCtrlSetEx
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_GetSet_E_FpExcptCtrlSetEx, *PST_GetSet_E_FpExcptCtrlSetEx;
#endif

typedef struct _ST_GetSet_ITComObject
{
	PVOID pInst;
	ITComObject* ipParam;
} ST_GetSet_ITComObject, *PST_GetSet_ITComObject;

#if defined(_X86_)
typedef struct _ST_GetSet_BOOL
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[3];
} ST_GetSet_BOOL, *PST_GetSet_BOOL;
#elif defined(_X64_)
typedef struct _ST_GetSet_BOOL
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[7];
} ST_GetSet_BOOL, *PST_GetSet_BOOL;
#endif

typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit
{
	PVOID pInst;
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stReInit;
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit;



#endif // _ExceptionGeneratorDuts__h_INCLUDED
