
// ****************** ExceptionGeneratorClassFactory.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorClassFactory__h_INCLUDED
#define _ExceptionGeneratorClassFactory__h_INCLUDED

#include "TcMatSimCFServiceProvider.h"

class CExceptionGeneratorClassFactory : public CObjClassFactory
{
protected:
	DECLARE_REPOSITORY_DRIVER()
public:
	CExceptionGeneratorClassFactory();

	// ITComClassFactory
	DECLARE_CLASS_MAP()
	DECLARE_FUNC_MAP()

	DECLARE_MGCLASSFACTORY_CONNECT()
};

#endif // _ExceptionGeneratorClassFactory__h_INCLUDED
			