// ****************** ExceptionGeneratorInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorInterfaces__h_INCLUDED
#define _ExceptionGeneratorInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ExceptionGeneratorServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_2806F198_B249_AEA0_AA4A_5EEEC04F9418_INCLUDED_)
#define _TC_TYPE_2806F198_B249_AEA0_AA4A_5EEEC04F9418_INCLUDED_
struct __declspec(novtable) ITcExceptionGenerator : ITcUnknown 
{
	virtual HRESULT TCOMAPI step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcExceptionGenerator, IID_ITcExceptionGenerator);
#endif // !defined(_TC_TYPE_2806F198_B249_AEA0_AA4A_5EEEC04F9418_INCLUDED_)



#endif // _ExceptionGeneratorInterfaces__h_INCLUDED
