// ****************** ExceptionGeneratorServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorServices__h_INCLUDED
#define _ExceptionGeneratorServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "ExceptionGeneratorVersion.h"
#define SRVNAME_ExceptionGenerator "ExceptionGenerator"

// TcCOM-ClassID of CTcComExceptionGenerator: {D2240B5B-5D52-0328-4960-51BFE295F729}
const CTCID CID_EXCEPTIONGENERATOR = {0xD2240B5B, 0x5D52, 0x0328, {0x49, 0x60, 0x51, 0xBF, 0xE2, 0x95, 0xF7, 0x29}};
// TcCOM-ClassID of CFbExceptionGenerator: {F2AB6118-079A-8496-79C0-827F85F83BB3}
const CTCID CID_FB_EXCEPTIONGENERATOR = {0xF2AB6118, 0x079A, 0x8496, {0x79, 0xC0, 0x82, 0x7F, 0x85, 0xF8, 0x3B, 0xB3}};
// TcCOM-ClassID of CFbTcComExceptionGenerator: {0B5C67B7-E2DB-6EBE-F0AE-4551EAB365F3}
const CTCID CID_FB_EXCEPTIONGENERATOR_TCCOM_INITSTRUCT = {0x0B5C67B7, 0xE2DB, 0x6EBE, {0xF0, 0xAE, 0x45, 0x51, 0xEA, 0xB3, 0x65, 0xF3}};


#ifndef ExceptionGenerator_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_4F85C72C_E14A_892A_773A_04CECD8E9B34_INCLUDED_)
#define _TC_TYPE_4F85C72C_E14A_892A_773A_04CECD8E9B34_INCLUDED_
typedef struct _ExtU_ExceptionGenerator_T
{
	bool DivByZero;
	bool FloatingPoint;
} ExtU_ExceptionGenerator_T, *PExtU_ExceptionGenerator_T;
#endif // !defined(_TC_TYPE_4F85C72C_E14A_892A_773A_04CECD8E9B34_INCLUDED_)

#if !defined(_TC_TYPE_15C3BEC8_8EAF_B5CB_6BDB_1310C9D8FF77_INCLUDED_)
#define _TC_TYPE_15C3BEC8_8EAF_B5CB_6BDB_1310C9D8FF77_INCLUDED_
typedef struct _ExtY_ExceptionGenerator_T
{
	double Result;
	double Counter;
} ExtY_ExceptionGenerator_T, *PExtY_ExceptionGenerator_T;
#endif // !defined(_TC_TYPE_15C3BEC8_8EAF_B5CB_6BDB_1310C9D8FF77_INCLUDED_)

#if !defined(_TC_TYPE_14C801D8_6BBA_3849_71A1_D5E04697759C_INCLUDED_)
#define _TC_TYPE_14C801D8_6BBA_3849_71A1_D5E04697759C_INCLUDED_
typedef struct _DW_ExceptionGenerator_T
{
	double Counter;
	double a;
	double b;
	double fPosInf;
	double fNegInf;
} DW_ExceptionGenerator_T, *PDW_ExceptionGenerator_T;
#endif // !defined(_TC_TYPE_14C801D8_6BBA_3849_71A1_D5E04697759C_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("FBFD65D3-5B51-29F7-664A-CF48F555967E", ITcExceptionGenerator)



#endif // _ExceptionGeneratorServices__h_INCLUDED
