
// ****************** ExceptionGeneratorCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorCtrl__h_INCLUDED
#define _ExceptionGeneratorCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CExceptionGeneratorDrvName "ExceptionGenerator"

#include "ExceptionGeneratorW32Resource.h"
#include "ExceptionGeneratorW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "ExceptionGeneratorClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CExceptionGeneratorCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CExceptionGeneratorCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CExceptionGeneratorCtrl, CExceptionGeneratorClassFactory>
{
public:
	CExceptionGeneratorCtrl() : ITcOCFCtrlImpl<CExceptionGeneratorCtrl, CExceptionGeneratorClassFactory>(){}

	virtual ~CExceptionGeneratorCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_ExceptionGeneratorCtrl)
DECLARE_NOT_AGGREGATABLE(CExceptionGeneratorCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CExceptionGeneratorCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _ExceptionGeneratorCtrl__h_INCLUDED