// ****************** ExceptionGeneratorDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorDuts__h_INCLUDED
#define _ExceptionGeneratorDuts__h_INCLUDED
#include "ExceptionGeneratorServices.h"

#if defined(_X86_)
typedef struct _ST_FB_afterinit_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_afterinit_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_afterinit_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_FB_afterinit_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_afterinit_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_afterinit_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
} ST_SetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_SetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	USHORT result;
	unsigned char reserved1[2];
} ST_GetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	USHORT result;
	unsigned char reserved1[6];
} ST_GetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE result;
} ST_GetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE result;
	unsigned char reserved1[4];
} ST_GetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE eParam;
} ST_SeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE eParam;
	unsigned char reserved1[4];
} ST_SeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
} ST_SetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
	unsigned char reserved1[4];
} ST_SetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
} ST_GetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
	unsigned char reserved1[4];
} ST_GetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
} ST_SetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_SetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskOid_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcTraceLevel result;
} ST_GeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcTraceLevel result;
	unsigned char reserved1[4];
} ST_GeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[3];
} ST_SetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[7];
} ST_SetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::CallerVerification result;
} ST_GeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::CallerVerification result;
	unsigned char reserved1[4];
} ST_GeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
} ST_GetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
	unsigned char reserved1[4];
} ST_GetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

typedef struct _ST_SetipTcComObject_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ITComObject* ipParam;
} ST_SetipTcComObject_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetipTcComObject_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_FB_exit_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_exit_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_exit_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_FB_exit_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_exit_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_exit_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG result;
} ST_GetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONGLONG result;
} ST_GetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet result;
	unsigned char reserved1[3];
} ST_GeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet result;
	unsigned char reserved1[7];
} ST_GeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
} ST_SeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
	unsigned char reserved1[4];
} ST_SeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct
{
	TCOM_STATE eObjState;
	OTCID nOid;
	OTCID nTaskOid;
	ULONG nTaskPriority;
	ULONG nTaskCycleTimeNs;
	USHORT nTaskPort;
	unsigned char reserved1[2];
	ULONG nTaskSortOrder;
	TcTraceLevel eTraceLevelMax;
	TcMgSdk::ModuleCaller eModuleCaller;
	TcMgSdk::CallerVerification eCallerVerification;
	TcMgSdk::StepSizeAdaptation eStepSizeAdaptation;
	TcMgSdk::ExecutionSequence1 eExecutionSequence;
	bool bExecute;
	unsigned char reserved2[3];
	TCOM_STATE eAccessLockState;
	TcMgSdk::FpExcptCtrlSet eInitExceptionHandling;
	TcMgSdk::FpExcptCtrlSet eUpdateExceptionHandling;
	unsigned char reserved3[2];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_FB_init_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stInit;
	bool result;
	unsigned char reserved2[3];
} ST_FB_init_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_init_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_FB_init_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stInit;
	bool result;
	unsigned char reserved2[7];
} ST_FB_init_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_init_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

typedef struct _ST_Reinit_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stReInit;
	bool result;
	unsigned char reserved1[3];
} ST_Reinit_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_Reinit_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_SetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
} ST_SetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
	unsigned char reserved1[4];
} ST_SetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_FB_Main_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_Main_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_Main_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_FB_Main_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_Main_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_Main_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet result;
	unsigned char reserved1[3];
} ST_GeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet result;
	unsigned char reserved1[7];
} ST_GeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcTraceLevel eParam;
} ST_SeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcTraceLevel eParam;
	unsigned char reserved1[4];
} ST_SeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteTraceLevelMax_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_FB_exit_FB_ExceptionGenerator
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_exit_FB_ExceptionGenerator, *PST_FB_exit_FB_ExceptionGenerator;
#elif defined(_X64_)
typedef struct _ST_FB_exit_FB_ExceptionGenerator
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_exit_FB_ExceptionGenerator, *PST_FB_exit_FB_ExceptionGenerator;
#endif

#if defined(_X86_)
typedef struct _ST_FB_Main_FB_ExceptionGenerator
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_Main_FB_ExceptionGenerator, *PST_FB_Main_FB_ExceptionGenerator;
#elif defined(_X64_)
typedef struct _ST_FB_Main_FB_ExceptionGenerator
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_Main_FB_ExceptionGenerator, *PST_FB_Main_FB_ExceptionGenerator;
#endif

#if defined(_X86_)
typedef struct _ST_SeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
} ST_SeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
	unsigned char reserved1[4];
} ST_SeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteCallerVerification_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_GetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_GetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_GetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_GetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetbExecute_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation result;
} ST_GeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation result;
	unsigned char reserved1[4];
} ST_GeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteStepSizeAdaptation_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo result;
} ST_GetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo result;
	unsigned char reserved1[4];
} ST_GetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetstInitExceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG nParam;
} ST_SetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONGLONG nParam;
} ST_SetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnExceptionCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_FB_init_FB_ExceptionGenerator
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1;
} ST_FB_init_FB_ExceptionGenerator, *PST_FB_init_FB_ExceptionGenerator;
#elif defined(_X64_)
typedef struct _ST_FB_init_FB_ExceptionGenerator
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[5];
} ST_FB_init_FB_ExceptionGenerator, *PST_FB_init_FB_ExceptionGenerator;
#endif

#if defined(_X86_)
typedef struct _ST_GeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE result;
} ST_GeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE result;
	unsigned char reserved1[4];
} ST_GeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteAccessLockState_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
} ST_SeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
	unsigned char reserved1[4];
} ST_SeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[3];
} ST_SetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[7];
} ST_SetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetbInitialized_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG nParam;
} ST_SetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONGLONG nParam;
} ST_SetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
} ST_SetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_SetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo result;
} ST_GetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo result;
	unsigned char reserved1[4];
} ST_GetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo result;
} ST_GetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo result;
	unsigned char reserved1[4];
} ST_GetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetstModuleBuildInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

typedef struct _ST_GetipADI_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ITcADI* result;
} ST_GetipADI_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetipADI_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_SeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
} ST_SeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
	unsigned char reserved1[4];
} ST_SeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleCaller result;
} ST_GeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ModuleCaller result;
	unsigned char reserved1[4];
} ST_GeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteModuleCaller_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
} ST_SetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
	unsigned char reserved1[4];
} ST_SetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetstExeceptionInfo_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_SeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_SeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteUpdateExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

typedef struct _ST_SetipADI_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ITcADI* ipParam;
} ST_SetipADI_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetipADI_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_GetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
} ST_GetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
	unsigned char reserved1[4];
} ST_GetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskPriority_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG result;
} ST_GetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONGLONG result;
} ST_GetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnCycleCount_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE eParam;
} ST_SetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TCOM_STATE eParam;
	unsigned char reserved1[4];
} ST_SetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnObjectState_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_GeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 result;
} ST_GeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 result;
	unsigned char reserved1[4];
} ST_GeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GeteExecutionSequence_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[2];
} ST_SetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[6];
} ST_SetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskPort_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

typedef struct _ST_GetipTcComObject_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ITComObject* result;
} ST_GetipTcComObject_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetipTcComObject_FB_ExceptionGenerator_TcCOM_InitStruct;

#if defined(_X86_)
typedef struct _ST_GetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
} ST_GetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_GetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG result;
	unsigned char reserved1[4];
} ST_GetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_GetnTaskCycleTimeNs_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_SeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_SeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SeteInitExceptionHandling_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif

#if defined(_X86_)
typedef struct _ST_SetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
} ST_SetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct;
#elif defined(_X64_)
typedef struct _ST_SetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_SetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_SetnTaskSortOrder_FB_ExceptionGenerator_TcCOM_InitStruct;
#endif



#endif // _ExceptionGeneratorDuts__h_INCLUDED
