// ****************** ExceptionGeneratorW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "ExceptionGeneratorCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_ExceptionGeneratorCtrl		=  {0x1DE9942D, 0x5FCE, 0x4970, {0xB4, 0x08, 0xCE, 0x9C, 0x54, 0xCD, 0xD8, 0xA4}};
const   CLSID   LIBID_ExceptionGeneratorW32Lib	=  {0x74B832A9, 0x2376, 0x4C0C, {0x8A, 0x28, 0xE0, 0x1E, 0x4F, 0x29, 0x40, 0xE1}};
const   CLSID   CLSID_ExceptionGeneratorCtrl   =  {0x1351DA2E, 0x4D3C, 0x4C85, {0x97, 0x8E, 0xD1, 0x17, 0xCE, 0x6D, 0x08, 0x08}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_ExceptionGeneratorCtrl, CExceptionGeneratorCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CExceptionGeneratorCtrl>* pCExceptionGeneratorCtrl = new CComObject<CExceptionGeneratorCtrl>();
	if (pCExceptionGeneratorCtrl == NULL) return E_POINTER;
	return pCExceptionGeneratorCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
