
// ****************** ExceptionGeneratorClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "ExceptionGeneratorClassFactory.h"
#include "ExceptionGeneratorServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComExceptionGenerator (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbExceptionGenerator);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbTcComExceptionGenerator);


DEFINE_REPOSITORY_DRIVER(CExceptionGeneratorClassFactory, ExceptionGenerator_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CExceptionGeneratorClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_ExceptionGenerator,CID_EXCEPTIONGENERATOR, SRVNAME_ExceptionGenerator "!CTcComExceptionGenerator", Create_CTcComExceptionGenerator)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CExceptionGeneratorClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbExceptionGenerator)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbTcComExceptionGenerator)

END_FUNC_MAP()

CExceptionGeneratorClassFactory::CExceptionGeneratorClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_ExceptionGenerator)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ExceptionGenerator));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ExceptionGenerator));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CExceptionGeneratorClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			