// ****************** TcComExceptionGenerator.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "TcComExceptionGenerator.h"

#ifdef EXT_MODE
#include "TcExtWork.h"
#endif


#include "ObjClassFactory.h"
using namespace TcMgSdk;


///////////////////////////////////////////////////////////////////////////////
// Definitions
///////////////////////////////////////////////////////////////////////////////
#ifdef _DEBUG
#define new DEBUG_NEW
#endif
#if TC_BUILD<=4024
DEFINE_THIS_FILE()
#endif

///////////////////////////////////////////////////////////////////////////////
// CTcComExceptionGenerator specific globals
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CTcComExceptionGenerator static members
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CTcComExceptionGenerator implementation
///////////////////////////////////////////////////////////////////////////////
BEGIN_INTERFACE_MAP(CTcComExceptionGenerator)
INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcPersist,ITcPersist)
	INTERFACE_ENTRY(IID_ITComObject,ITComObject)
	INTERFACE_ENTRY(IID_ITcWatchSource,ITcWatchSource)
	INTERFACE_ENTRY(IID_ITcCyclic,ITcCyclic)
	INTERFACE_ENTRY(IID_ITcPostCyclic,ITcPostCyclic)
	INTERFACE_ENTRY(IID_ITcADI,ITcADI)
	INTERFACE_ENTRY(IID_ITcExceptionGenerator,ITcExceptionGenerator)
END_INTERFACE_MAP()

IMPLEMENT_ITCWATCHSOURCE(CTcComExceptionGenerator)

BEGIN_OBJDATAAREA_MAP(CTcComExceptionGenerator)
	OBJDATAAREA_SPAN_PTR_SIZE_FLAGS( 0, 1, &(ExceptionGenerator_Obj.ExceptionGenerator_U.DivByZero), 2, 0)
	OBJDATAAREA_SPAN_PTR_SIZE_FLAGS( 1, 1, &(ExceptionGenerator_Obj.ExceptionGenerator_Y.Result), 16, OBJDATAAREA_DISABLE_SET)
	OBJDATAAREA_SPAN_PTR_SIZE_FLAGS( 2, 1, &(ExceptionGenerator_Obj.ExceptionGenerator_DW.Counter), 40, OBJDATAAREA_DISABLE_SET)
	OBJDATAAREA_SPAN_PTR_SIZE_FLAGS( 3, 1, &m_ContextInfo[0].Execution, sizeof(m_ContextInfo[0].Execution), OBJDATAAREA_DISABLE_SET)
END_OBJDATAAREA_MAP()

BEGIN_SETOBJPARA_MAP2(CTcComExceptionGenerator,TcMatSim::GeneratedTcCom)
	SETOBJPARA_DATAAREA_MAP()
	SETOBJPARA_VALUE(0x00000001,m_TraceLevelMax)
	SETOBJPARA_VALUE(0x00000002,m_ModuleCaller)
	SETOBJPARA_VALUE(0x00000003,m_CallerVerification)
	SETOBJPARA_VALUE(0x00000004,m_StepSizeAdaptation)
	SETOBJPARA_VALUE(0x00000005,m_ExecutionSequence)
	SETOBJPARA_VALUE(0x00000006,m_Execute)
	SETOBJPARA_VALUE(0x00000007,m_AccessLockState)
	SETOBJPARA_VALUE(0x00000008,GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init))
	SETOBJPARA_VALUE(0x00000009,GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update))
	SETOBJPARA_VALUE_DENIED(0x0000000a,m_ModuleBuildInfo)
	SETOBJPARA_VALUE_DENIED(0x0000000b,m_Initialized)
	SETOBJPARA_VALUE_DENIED(0x0000000c,&m_ContextInfo[0].Execution.CycleCount)
	SETOBJPARA_VALUE_DENIED(0x0000000d,&m_ContextInfo[0].Execution.ExceptionCount)
	SETOBJPARA_VALUE_DENIED(0x0000000e,&m_ContextInfo[0].Execution.ActException)
END_SETOBJPARA_MAP2(TcMatSim::GeneratedTcCom)

BEGIN_GETOBJPARA_MAP2(CTcComExceptionGenerator,TcMatSim::GeneratedTcCom)
	GETOBJPARA_DATAAREA_MAP()
	GETOBJPARA_VALUE(0x00000001,m_TraceLevelMax)
	GETOBJPARA_VALUE(0x00000002,m_ModuleCaller)
	GETOBJPARA_VALUE(0x00000003,m_CallerVerification)
	GETOBJPARA_VALUE(0x00000004,m_StepSizeAdaptation)
	GETOBJPARA_VALUE(0x00000005,m_ExecutionSequence)
	GETOBJPARA_VALUE(0x00000006,m_Execute)
	GETOBJPARA_VALUE(0x00000007,m_AccessLockState)
	GETOBJPARA_VALUE(0x00000008,GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init))
	GETOBJPARA_VALUE(0x00000009,GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update))
	GETOBJPARA_VALUE_LOCK(0x0000000a, m_ModuleBuildInfo, 0, VarAccess(Access::Read))
	GETOBJPARA_VALUE_LOCK(0x0000000b, m_Initialized, 0, VarAccess(Access::Read))
	GETOBJPARA_PTR_SIZE(0x0000000c,&m_ContextInfo[0].Execution.CycleCount,sizeof(m_ContextInfo[0].Execution.CycleCount))
	GETOBJPARA_PTR_SIZE(0x0000000d,&m_ContextInfo[0].Execution.ExceptionCount,sizeof(m_ContextInfo[0].Execution.ExceptionCount))
	GETOBJPARA_PTR_SIZE(0x0000000e,&m_ContextInfo[0].Execution.ActException,sizeof(m_ContextInfo[0].Execution.ActException))
END_GETOBJPARA_MAP2(TcMatSim::GeneratedTcCom)

BEGIN_OBJPARAWATCH_MAP2(CTcComExceptionGenerator)
	OBJPARAWATCH_DATAAREA_MAP()
	OBJPARAWATCH_VALUE(0x00000001,m_TraceLevelMax)
	OBJPARAWATCH_VALUE(0x00000002,m_ModuleCaller)
	OBJPARAWATCH_VALUE(0x00000003,m_CallerVerification)
	OBJPARAWATCH_VALUE(0x00000004,m_StepSizeAdaptation)
	OBJPARAWATCH_VALUE(0x00000005,m_ExecutionSequence)
	OBJPARAWATCH_VALUE(0x00000006,m_Execute)
	OBJPARAWATCH_VALUE(0x00000007,m_AccessLockState)
	OBJPARAWATCH_VALUE(0x00000008,GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init))
	OBJPARAWATCH_VALUE(0x00000009,GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update))
	OBJPARAWATCH_VALUE(0x0000000a,m_ModuleBuildInfo)
	OBJPARAWATCH_VALUE(0x0000000b,m_Initialized)
	OBJPARAWATCH_PTR_SIZE(0x0000000c,&m_ContextInfo[0].Execution.CycleCount,sizeof(m_ContextInfo[0].Execution.CycleCount))
	OBJPARAWATCH_PTR_SIZE(0x0000000d,&m_ContextInfo[0].Execution.ExceptionCount,sizeof(m_ContextInfo[0].Execution.ExceptionCount))
	OBJPARAWATCH_PTR_SIZE(0x0000000e,&m_ContextInfo[0].Execution.ActException,sizeof(m_ContextInfo[0].Execution.ActException))
END_OBJPARAWATCH_MAP2(TcMatSim::GeneratedTcCom)

IMPLEMENT_ITCADI(CTcComExceptionGenerator)

IMPLEMENT_IPERSIST_LIB(CTcComExceptionGenerator,VID_ExceptionGenerator,CID_EXCEPTIONGENERATOR)

// State transition: Init -> PreOp
HRESULT CTcComExceptionGenerator::SetObjStateIP(ITComObjectServer* ipSrv, TComInitDataHdr* pInitData)
{
	HRESULT hr = S_OK;

	if (SUCCEEDED(hr))
		hr = SingleInstanceLock(GUID_NULL);
	if (SUCCEEDED(hr))
	{
		m_ContextInfo[0].OriginalTid = 0;
		m_ContextInfo[0].OriginalSampleTime = 0.01;

	}
	if (SUCCEEDED(hr))
	{

	}
	if (FAILED(hr))
	{
		SetObjStatePI();
	}
	return hr;
}

// State transition: PreOp -> SafeOp
HRESULT CTcComExceptionGenerator::SetObjStatePS(TComInitDataHdr* pInitData)
{
	HRESULT hr = S_OK;


	if(SUCCEEDED(hr))
		hr = VerifyFpExceptCtrlSets();
	if(SUCCEEDED(hr))
	{
		auto fpState = FpControl(FpCtrlSection::Init);
		ExceptionGenerator_Obj.initialize();

		if (SUCCEEDED(hr))
			hr = CheckAndAdaptCycleTimes();
		m_Initialized = SUCCEEDED(hr);
		FpRestore(fpState);
	}

	if (FAILED(hr))
	{
		SetObjStateSP();
	}
	return hr;
}

// State transition: SafeOp -> Op
HRESULT CTcComExceptionGenerator::SetObjStateSO()
{
	HRESULT hr = S_OK;

	if (FAILED(hr))
	{
		SetObjStateOS();
	}
	return hr;
}

// State transition: Op -> SafeOp
HRESULT CTcComExceptionGenerator::SetObjStateOS()
{
	HRESULT hr = S_OK;

	return hr;
}

// State transition: SafeOp -> PreOp
HRESULT CTcComExceptionGenerator::SetObjStateSP()
{
	HRESULT hr = S_OK;

	auto fpState = FpControl(FpCtrlSection::Init);
	FpRestore(fpState);

	m_Initialized = false;

	return hr;
}

// State transition: PreOp -> Init
HRESULT CTcComExceptionGenerator::SetObjStatePI()
{
	HRESULT hr = S_OK;

	auto fpState = FpControl(FpCtrlSection::Init);
	ExceptionGenerator_Obj.terminate();

	FpRestore(fpState);
	SingleInstanceRelease();

	return hr;
}

// Constructor
CTcComExceptionGenerator::CTcComExceptionGenerator() :
	TcMatSim::GeneratedTcCom(1,0,TC_BUILD_MIN)
{
	m_TraceLevelMax = tlInfo;
	m_ModuleCaller = ModuleCaller::CyclicTask;
	m_CallerVerification = CallerVerification::Default;
	m_StepSizeAdaptation = StepSizeAdaptation::RequireMatchingTaskCycleTime;
	m_ExecutionSequence = ExecutionSequence2::UpdateBeforeOutputMapping;
	m_Execute = false;
	m_AccessLockState = TCOM_STATE_OP;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_CallerExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_LogCatchAndDump;
	m_Initialized = 0;

#ifdef _DEBUG
	m_ModuleBuildInfo.Debug = true;
#else
	m_ModuleBuildInfo.Debug = false;
#endif
	m_ModuleBuildInfo.TcBuild = TC_BUILD;
	m_ModuleBuildInfo.TcRevision = TC_REVISION;

}

// Destructor
CTcComExceptionGenerator::~CTcComExceptionGenerator()
{

}

HRESULT TCOMAPI CTcComExceptionGenerator::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{

	if (!m_Execute)
		return S_FALSE;
	if (!m_Initialized)
		return ADS_E_NOTINIT;
	if (m_ExecutionSequence!=TcMgSdk::ExecutionSequence2::UpdateBeforeOutputMapping)
		return S_OK;
	m_ContextInfo[context].ExecutingCyclicCall = true;
	HRESULT hr = Update(ipTask, context);
	m_ContextInfo[context].ExecutingCyclicCall = false;
	return hr;
}

HRESULT TCOMAPI CTcComExceptionGenerator::PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{

	if (!m_Execute)
		return S_FALSE;
	if (!m_Initialized)
		return ADS_E_NOTINIT;
	if (m_ExecutionSequence!=TcMgSdk::ExecutionSequence2::IoAtTaskBegin)
		return S_OK;
	m_ContextInfo[context].ExecutingPostCyclicCall = true;
	HRESULT hr = Update(ipTask, context);
	m_ContextInfo[context].ExecutingPostCyclicCall = false;
	return hr;
}

HRESULT CTcComExceptionGenerator::Update(ITcTask* ipTask, ULONG_PTR context)
{
	HRESULT hr = SynchronizeTasks(context);
	if(SUCCEEDED(hr))
		hr = VerifyCaller(ipTask, context);

	if(SUCCEEDED(hr) && m_ContextInfo[context].Synchronized)
	{
		m_ContextInfo[context].Execution.CycleCount++;
		auto fpState = FpControl(FpCtrlSection::Update);
		TcTry
		{
			hr = EvalMdlErrorStatus(ExceptionGenerator_Obj.getRTM()->errorStatus,false);
			if (hr == S_OK)
			{
				ExceptionGenerator_Obj.step();
				EvalMdlErrorStatus(ExceptionGenerator_Obj.getRTM()->errorStatus,true);
			}

		}
		TcExcept(ExceptionFilter(ipTask, GetExceptionInformation(), static_cast<LONG>(context)))
		{
			ExceptionHandler();
		}
		FpRestore(fpState);
	}

	return hr;

}

HRESULT CTcComExceptionGenerator::CheckAndAdaptCycleTimes()
{
	double fCycleTimeMultiplier = 1;
	HRESULT hr = CheckCycleTimes(fCycleTimeMultiplier);
	return hr;
}

// ITcExceptionGenerator
HRESULT TCOMAPI CTcComExceptionGenerator::step()
{
	HRESULT hr = S_OK;
	auto fpState = FpControl(FpCtrlSection::Update);

	ExceptionGenerator_Obj.step();


	FpRestore(fpState);
	return hr;
}




HRESULT TCOMAPI Create_CTcComExceptionGenerator (PITCID pIid, PPVOID pipItf)
{
	return Create<CTcComExceptionGenerator>(*pIid, pipItf);
}
