// ****************** TcComExceptionGenerator.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.4.1.0
// MATLAB 9.11.0.1837725 (R2021b) Update 2 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.4.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _TcComExceptionGenerator__h_INCLUDED
#define _TcComExceptionGenerator__h_INCLUDED


#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcMatSimTcCom.h"
#include "ExceptionGenerator.h"
#include "ExceptionGeneratorInternal.h"

#include "ExceptionGeneratorInterfaces.h"
#include "ExceptionGeneratorVersion.h"


class CTcComExceptionGenerator :
	public TcMatSim::GeneratedTcCom,
	public ITcWatchSource,
	public ITcCyclic,
	public ITcPostCyclic,
	public ITcADI,
	public ITcExceptionGenerator
{
public:
	DECLARE_IUNKNOWN_DERIVED()
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_PARA()
	DECLARE_ITCADI()
	DECLARE_IPERSIST_LIB()


	// Constructor
	CTcComExceptionGenerator();

	// Destructor
	~CTcComExceptionGenerator();

	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT Update(ITcTask* ipTask, ULONG_PTR context);
	HRESULT CheckAndAdaptCycleTimes();

	// ITcExceptionGenerator
	HRESULT TCOMAPI step();



	ExceptionGeneratorModelClass ExceptionGenerator_Obj;



};
			

#endif // _TcComExceptionGenerator__h_INCLUDED