
// ****************** ExceptionGeneratorClassFactory.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.1.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.8.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorClassFactory__h_INCLUDED
#define _ExceptionGeneratorClassFactory__h_INCLUDED

#include "TcMatSimCFServiceProvider.h"

class CExceptionGeneratorClassFactory : public CObjClassFactory
{
protected:
	DECLARE_REPOSITORY_DRIVER()
public:
	CExceptionGeneratorClassFactory();

	// ITComClassFactory
	DECLARE_CLASS_MAP()
	DECLARE_FUNC_MAP()

	DECLARE_MGCLASSFACTORY_CONNECT()
	const GUID VID_DataExchangeModules = {0xC268C31A, 0x1F4A, 0x8348, {0x27, 0x53, 0x97, 0x0E, 0x95, 0x3E, 0xCF, 0xC3}};
			
};

#endif // _ExceptionGeneratorClassFactory__h_INCLUDED
			