// ****************** ExceptionGeneratorInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.1.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.8.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorInternal__h_INCLUDED
#define _ExceptionGeneratorInternal__h_INCLUDED

#include "rtwtypes.h"
#include "rtGetInf.h"
#include "rtGetNaN.h"
#include "rt_nonfinite.h"
#include "ExceptionGenerator.h"
#include "ExceptionGenerator_private.h"
#include "ExceptionGenerator_types.h"
#include "multiword_types.h"
#include "rtmodel.h"
#include "rtw_continuous.h"
#include "rtw_solver.h"

#define ExceptionGenerator_TYPES 1

// DW_ExceptionGenerator_T
#ifndef _TC_TYPE_14C801D8_6BBA_3849_71A1_D5E04697759C_INCLUDED_
#define _TC_TYPE_14C801D8_6BBA_3849_71A1_D5E04697759C_INCLUDED_
#endif
TYPESIZE_VALIDATION(DW_ExceptionGenerator_T,40);

// ExtU_ExceptionGenerator_T
#ifndef _TC_TYPE_4F85C72C_E14A_892A_773A_04CECD8E9B34_INCLUDED_
#define _TC_TYPE_4F85C72C_E14A_892A_773A_04CECD8E9B34_INCLUDED_
#endif
TYPESIZE_VALIDATION(ExtU_ExceptionGenerator_T,2);

// ExtY_ExceptionGenerator_T
#ifndef _TC_TYPE_15C3BEC8_8EAF_B5CB_6BDB_1310C9D8FF77_INCLUDED_
#define _TC_TYPE_15C3BEC8_8EAF_B5CB_6BDB_1310C9D8FF77_INCLUDED_
#endif
TYPESIZE_VALIDATION(ExtY_ExceptionGenerator_T,16);

#endif // _ExceptionGeneratorInternal__h_INCLUDED