// ****************** ExceptionGeneratorDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.1.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.8.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorDuts__h_INCLUDED
#define _ExceptionGeneratorDuts__h_INCLUDED
#include "ExceptionGeneratorServices.h"



#if ExceptionGenerator_TYPES
#if !defined(_TC_TYPE_68C83077_AEF1_CA44_09E2_E86F46C8F1EA_INCLUDED_)
#define _TC_TYPE_68C83077_AEF1_CA44_09E2_E86F46C8F1EA_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_ExceptionGenerator_FB_Main, *PST_FB_ExceptionGenerator_FB_Main;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_ExceptionGenerator_FB_Main, *PST_FB_ExceptionGenerator_FB_Main;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_FB_Main = {0x68C83077, 0xAEF1, 0xCA44, {0x09, 0xE2, 0xE8, 0x6F, 0x46, 0xC8, 0xF1, 0xEA}};
#endif // !defined(_TC_TYPE_68C83077_AEF1_CA44_09E2_E86F46C8F1EA_INCLUDED_)

#if !defined(_TC_TYPE_7DE60945_ACC8_15C2_CF2F_E1806E1EE849_INCLUDED_)
#define _TC_TYPE_7DE60945_ACC8_15C2_CF2F_E1806E1EE849_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_ExceptionGenerator_FB_exit, *PST_FB_ExceptionGenerator_FB_exit;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_ExceptionGenerator_FB_exit, *PST_FB_ExceptionGenerator_FB_exit;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_FB_exit = {0x7DE60945, 0xACC8, 0x15C2, {0xCF, 0x2F, 0xE1, 0x80, 0x6E, 0x1E, 0xE8, 0x49}};
#endif // !defined(_TC_TYPE_7DE60945_ACC8_15C2_CF2F_E1806E1EE849_INCLUDED_)

#if !defined(_TC_TYPE_A0105400_DF5D_92F1_C469_7F75B2202D3F_INCLUDED_)
#define _TC_TYPE_A0105400_DF5D_92F1_C469_7F75B2202D3F_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1;
} ST_FB_ExceptionGenerator_FB_init, *PST_FB_ExceptionGenerator_FB_init;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[5];
} ST_FB_ExceptionGenerator_FB_init, *PST_FB_ExceptionGenerator_FB_init;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_FB_init = {0xA0105400, 0xDF5D, 0x92F1, {0xC4, 0x69, 0x7F, 0x75, 0xB2, 0x20, 0x2D, 0x3F}};
#endif // !defined(_TC_TYPE_A0105400_DF5D_92F1_C469_7F75B2202D3F_INCLUDED_)

#if !defined(_TC_TYPE_A918DBD2_68B1_96AB_5085_001E1E537F56_INCLUDED_)
#define _TC_TYPE_A918DBD2_68B1_96AB_5085_001E1E537F56_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_HRESULT
{
	PVOID pInst;
	HRESULT nParam;
} ST_GetSet_HRESULT, *PST_GetSet_HRESULT;
#elif defined(_X64_)
typedef struct _ST_GetSet_HRESULT
{
	PVOID pInst;
	HRESULT nParam;
	unsigned char reserved1[4];
} ST_GetSet_HRESULT, *PST_GetSet_HRESULT;
#endif
const GUID GUID_ST_GetSet_HRESULT = {0xA918DBD2, 0x68B1, 0x96AB, {0x50, 0x85, 0x00, 0x1E, 0x1E, 0x53, 0x7F, 0x56}};
#endif // !defined(_TC_TYPE_A918DBD2_68B1_96AB_5085_001E1E537F56_INCLUDED_)

#if !defined(_TC_TYPE_5F7BDFDC_E1B9_123D_8C10_6D0E9AB2C24F_INCLUDED_)
#define _TC_TYPE_5F7BDFDC_E1B9_123D_8C10_6D0E9AB2C24F_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_FpExcptCtrlSetEx
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_GetSet_E_FpExcptCtrlSetEx, *PST_GetSet_E_FpExcptCtrlSetEx;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_FpExcptCtrlSetEx
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_GetSet_E_FpExcptCtrlSetEx, *PST_GetSet_E_FpExcptCtrlSetEx;
#endif
const GUID GUID_ST_GetSet_E_FpExcptCtrlSetEx = {0x5F7BDFDC, 0xE1B9, 0x123D, {0x8C, 0x10, 0x6D, 0x0E, 0x9A, 0xB2, 0xC2, 0x4F}};
#endif // !defined(_TC_TYPE_5F7BDFDC_E1B9_123D_8C10_6D0E9AB2C24F_INCLUDED_)

#if !defined(_TC_TYPE_2EC54308_2713_3F94_E215_86E37835329A_INCLUDED_)
#define _TC_TYPE_2EC54308_2713_3F94_E215_86E37835329A_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_ULINT
{
	PVOID pInst;
	unsigned char reserved1[4];
	ULONGLONG nParam;
} ST_GetSet_ULINT, *PST_GetSet_ULINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_ULINT
{
	PVOID pInst;
	ULONGLONG nParam;
} ST_GetSet_ULINT, *PST_GetSet_ULINT;
#endif
const GUID GUID_ST_GetSet_ULINT = {0x2EC54308, 0x2713, 0x3F94, {0xE2, 0x15, 0x86, 0xE3, 0x78, 0x35, 0x32, 0x9A}};
#endif // !defined(_TC_TYPE_2EC54308_2713_3F94_E215_86E37835329A_INCLUDED_)

#if !defined(_TC_TYPE_77EBBD72_7A15_F03E_8800_BE22FCBBBC3E_INCLUDED_)
#define _TC_TYPE_77EBBD72_7A15_F03E_8800_BE22FCBBBC3E_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_ST_ExceptionInfo
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
} ST_GetSet_ST_ExceptionInfo, *PST_GetSet_ST_ExceptionInfo;
#elif defined(_X64_)
typedef struct _ST_GetSet_ST_ExceptionInfo
{
	PVOID pInst;
	TcMgSdk::ExceptionInfo stParam;
	unsigned char reserved1[4];
} ST_GetSet_ST_ExceptionInfo, *PST_GetSet_ST_ExceptionInfo;
#endif
const GUID GUID_ST_GetSet_ST_ExceptionInfo = {0x77EBBD72, 0x7A15, 0xF03E, {0x88, 0x00, 0xBE, 0x22, 0xFC, 0xBB, 0xBC, 0x3E}};
#endif // !defined(_TC_TYPE_77EBBD72_7A15_F03E_8800_BE22FCBBBC3E_INCLUDED_)

#if !defined(_TC_TYPE_FABBB492_0FDC_5010_369A_CF3F2D4FEBB9_INCLUDED_)
#define _TC_TYPE_FABBB492_0FDC_5010_369A_CF3F2D4FEBB9_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_BOOL
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[3];
} ST_GetSet_BOOL, *PST_GetSet_BOOL;
#elif defined(_X64_)
typedef struct _ST_GetSet_BOOL
{
	PVOID pInst;
	bool bParam;
	unsigned char reserved1[7];
} ST_GetSet_BOOL, *PST_GetSet_BOOL;
#endif
const GUID GUID_ST_GetSet_BOOL = {0xFABBB492, 0x0FDC, 0x5010, {0x36, 0x9A, 0xCF, 0x3F, 0x2D, 0x4F, 0xEB, 0xB9}};
#endif // !defined(_TC_TYPE_FABBB492_0FDC_5010_369A_CF3F2D4FEBB9_INCLUDED_)

#if !defined(_TC_TYPE_1217FAA4_17CB_013E_FFAA_C2794F2E7542_INCLUDED_)
#define _TC_TYPE_1217FAA4_17CB_013E_FFAA_C2794F2E7542_INCLUDED_
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct
{
	TCOM_STATE eObjState;
	STRING127 sObjName;
	OTCID nOid;
	OTCID nTaskOid;
	ULONG nTaskSortOrder;
	TcTraceLevel eTraceLevelMax;
	TcMgSdk::ModuleCaller eModuleCaller;
	TcMgSdk::CallerVerification eCallerVerification;
	TcMgSdk::StepSizeAdaptation eStepSizeAdaptation;
	TcMgSdk::ExecutionSequence1 eExecutionSequence;
	bool bExecute;
	unsigned char reserved1[3];
	TCOM_STATE eAccessLockState;
	TcMgSdk::FpExcptCtrlSet eInitExceptionHandling;
	TcMgSdk::FpExcptCtrlSet eUpdateExceptionHandling;
	unsigned char reserved2[2];
	TcMatSim_ModuleGeneratorInfo stModuleGeneratorInfo;
	TcMatSim_SimulinkModelInfo stSimulinkModelInfo;
} ST_FB_ExceptionGenerator_TcCOM_InitStruct, *PST_FB_ExceptionGenerator_TcCOM_InitStruct;
const GUID GUID_ST_FB_ExceptionGenerator_TcCOM_InitStruct = {0x1217FAA4, 0x17CB, 0x013E, {0xFF, 0xAA, 0xC2, 0x79, 0x4F, 0x2E, 0x75, 0x42}};
#endif // !defined(_TC_TYPE_1217FAA4_17CB_013E_FFAA_C2794F2E7542_INCLUDED_)

#if !defined(_TC_TYPE_1E999F97_2969_1EFE_1942_580411674B7D_INCLUDED_)
#define _TC_TYPE_1E999F97_2969_1EFE_1942_580411674B7D_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[2];
	ST_FB_ExceptionGenerator_TcCOM_InitStruct& stInit;
	bool result;
	unsigned char reserved2[3];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	unsigned char reserved1[6];
	ST_FB_ExceptionGenerator_TcCOM_InitStruct& stInit;
	bool result;
	unsigned char reserved2[7];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_init = {0x1E999F97, 0x2969, 0x1EFE, {0x19, 0x42, 0x58, 0x04, 0x11, 0x67, 0x4B, 0x7D}};
#endif // !defined(_TC_TYPE_1E999F97_2969_1EFE_1942_580411674B7D_INCLUDED_)

#if !defined(_TC_TYPE_68933FBF_3C01_E724_8E58_CE9E5B6125A2_INCLUDED_)
#define _TC_TYPE_68933FBF_3C01_E724_8E58_CE9E5B6125A2_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_afterinit = {0x68933FBF, 0x3C01, 0xE724, {0x8E, 0x58, 0xCE, 0x9E, 0x5B, 0x61, 0x25, 0xA2}};
#endif // !defined(_TC_TYPE_68933FBF_3C01_E724_8E58_CE9E5B6125A2_INCLUDED_)

#if !defined(_TC_TYPE_1E627526_0FB3_4AD8_A368_8AB7DA36A6DA_INCLUDED_)
#define _TC_TYPE_1E627526_0FB3_4AD8_A368_8AB7DA36A6DA_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit
{
	PVOID pInst;
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stReInit;
	bool result;
	unsigned char reserved1[3];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit
{
	PVOID pInst;
	ST_FB_ExceptionGenerator_TcCOM_InitStruct stReInit;
	bool result;
	unsigned char reserved1[7];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_TcCOM_InitStruct_Reinit = {0x1E627526, 0x0FB3, 0x4AD8, {0xA3, 0x68, 0x8A, 0xB7, 0xDA, 0x36, 0xA6, 0xDA}};
#endif // !defined(_TC_TYPE_1E627526_0FB3_4AD8_A368_8AB7DA36A6DA_INCLUDED_)

#if !defined(_TC_TYPE_DE283CFE_0094_B10A_6AA3_B79AA3D4B5A9_INCLUDED_)
#define _TC_TYPE_DE283CFE_0094_B10A_6AA3_B79AA3D4B5A9_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_Main = {0xDE283CFE, 0x0094, 0xB10A, {0x6A, 0xA3, 0xB7, 0x9A, 0xA3, 0xD4, 0xB5, 0xA9}};
#endif // !defined(_TC_TYPE_DE283CFE_0094_B10A_6AA3_B79AA3D4B5A9_INCLUDED_)

#if !defined(_TC_TYPE_C4B11E9F_1DC1_D052_0E34_5EF2BEADE120_INCLUDED_)
#define _TC_TYPE_C4B11E9F_1DC1_D052_0E34_5EF2BEADE120_INCLUDED_
#if defined(_X86_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit;
#elif defined(_X64_)
typedef struct _ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit, *PST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit;
#endif
const GUID GUID_ST_FB_ExceptionGenerator_TcCOM_InitStruct_FB_exit = {0xC4B11E9F, 0x1DC1, 0xD052, {0x0E, 0x34, 0x5E, 0xF2, 0xBE, 0xAD, 0xE1, 0x20}};
#endif // !defined(_TC_TYPE_C4B11E9F_1DC1_D052_0E34_5EF2BEADE120_INCLUDED_)

#if !defined(_TC_TYPE_2ED49A32_E84B_D386_A7E6_7977A4529361_INCLUDED_)
#define _TC_TYPE_2ED49A32_E84B_D386_A7E6_7977A4529361_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_TCOM_STATE
{
	PVOID pInst;
	TCOM_STATE eParam;
} ST_GetSet_TCOM_STATE, *PST_GetSet_TCOM_STATE;
#elif defined(_X64_)
typedef struct _ST_GetSet_TCOM_STATE
{
	PVOID pInst;
	TCOM_STATE eParam;
	unsigned char reserved1[4];
} ST_GetSet_TCOM_STATE, *PST_GetSet_TCOM_STATE;
#endif
const GUID GUID_ST_GetSet_TCOM_STATE = {0x2ED49A32, 0xE84B, 0xD386, {0xA7, 0xE6, 0x79, 0x77, 0xA4, 0x52, 0x93, 0x61}};
#endif // !defined(_TC_TYPE_2ED49A32_E84B_D386_A7E6_7977A4529361_INCLUDED_)

#if !defined(_TC_TYPE_07FB5F29_9630_3C20_6140_7ED32601F521_INCLUDED_)
#define _TC_TYPE_07FB5F29_9630_3C20_6140_7ED32601F521_INCLUDED_
typedef struct _ST_GetSet_ITComObject
{
	PVOID pInst;
	ITComObject* ipParam;
} ST_GetSet_ITComObject, *PST_GetSet_ITComObject;
const GUID GUID_ST_GetSet_ITComObject = {0x07FB5F29, 0x9630, 0x3C20, {0x61, 0x40, 0x7E, 0xD3, 0x26, 0x01, 0xF5, 0x21}};
#endif // !defined(_TC_TYPE_07FB5F29_9630_3C20_6140_7ED32601F521_INCLUDED_)

#if !defined(_TC_TYPE_858E8D33_8412_7D27_0C7E_D39D043AEF7C_INCLUDED_)
#define _TC_TYPE_858E8D33_8412_7D27_0C7E_D39D043AEF7C_INCLUDED_
typedef struct _ST_GetSet_ITcADI
{
	PVOID pInst;
	ITcADI* ipParam;
} ST_GetSet_ITcADI, *PST_GetSet_ITcADI;
const GUID GUID_ST_GetSet_ITcADI = {0x858E8D33, 0x8412, 0x7D27, {0x0C, 0x7E, 0xD3, 0x9D, 0x04, 0x3A, 0xEF, 0x7C}};
#endif // !defined(_TC_TYPE_858E8D33_8412_7D27_0C7E_D39D043AEF7C_INCLUDED_)

#if !defined(_TC_TYPE_CC495849_6A67_6C41_E597_58CDF011D4F4_INCLUDED_)
#define _TC_TYPE_CC495849_6A67_6C41_E597_58CDF011D4F4_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_OTCID
{
	PVOID pInst;
	OTCID nParam;
} ST_GetSet_OTCID, *PST_GetSet_OTCID;
#elif defined(_X64_)
typedef struct _ST_GetSet_OTCID
{
	PVOID pInst;
	OTCID nParam;
	unsigned char reserved1[4];
} ST_GetSet_OTCID, *PST_GetSet_OTCID;
#endif
const GUID GUID_ST_GetSet_OTCID = {0xCC495849, 0x6A67, 0x6C41, {0xE5, 0x97, 0x58, 0xCD, 0xF0, 0x11, 0xD4, 0xF4}};
#endif // !defined(_TC_TYPE_CC495849_6A67_6C41_E597_58CDF011D4F4_INCLUDED_)

#if !defined(_TC_TYPE_82F235ED_17E4_B64A_C37C_15DCC60F861B_INCLUDED_)
#define _TC_TYPE_82F235ED_17E4_B64A_C37C_15DCC60F861B_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_UDINT
{
	PVOID pInst;
	ULONG nParam;
} ST_GetSet_UDINT, *PST_GetSet_UDINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_UDINT
{
	PVOID pInst;
	ULONG nParam;
	unsigned char reserved1[4];
} ST_GetSet_UDINT, *PST_GetSet_UDINT;
#endif
const GUID GUID_ST_GetSet_UDINT = {0x82F235ED, 0x17E4, 0xB64A, {0xC3, 0x7C, 0x15, 0xDC, 0xC6, 0x0F, 0x86, 0x1B}};
#endif // !defined(_TC_TYPE_82F235ED_17E4_B64A_C37C_15DCC60F861B_INCLUDED_)

#if !defined(_TC_TYPE_BE5A5956_3957_8E47_A628_49BF59733E2A_INCLUDED_)
#define _TC_TYPE_BE5A5956_3957_8E47_A628_49BF59733E2A_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_UINT
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[2];
} ST_GetSet_UINT, *PST_GetSet_UINT;
#elif defined(_X64_)
typedef struct _ST_GetSet_UINT
{
	PVOID pInst;
	USHORT nParam;
	unsigned char reserved1[6];
} ST_GetSet_UINT, *PST_GetSet_UINT;
#endif
const GUID GUID_ST_GetSet_UINT = {0xBE5A5956, 0x3957, 0x8E47, {0xA6, 0x28, 0x49, 0xBF, 0x59, 0x73, 0x3E, 0x2A}};
#endif // !defined(_TC_TYPE_BE5A5956_3957_8E47_A628_49BF59733E2A_INCLUDED_)

#if !defined(_TC_TYPE_07A6092B_F404_D8D8_5A51_1979ED9F5609_INCLUDED_)
#define _TC_TYPE_07A6092B_F404_D8D8_5A51_1979ED9F5609_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_TcTraceLevel
{
	PVOID pInst;
	TcTraceLevel eParam;
} ST_GetSet_TcTraceLevel, *PST_GetSet_TcTraceLevel;
#elif defined(_X64_)
typedef struct _ST_GetSet_TcTraceLevel
{
	PVOID pInst;
	TcTraceLevel eParam;
	unsigned char reserved1[4];
} ST_GetSet_TcTraceLevel, *PST_GetSet_TcTraceLevel;
#endif
const GUID GUID_ST_GetSet_TcTraceLevel = {0x07A6092B, 0xF404, 0xD8D8, {0x5A, 0x51, 0x19, 0x79, 0xED, 0x9F, 0x56, 0x09}};
#endif // !defined(_TC_TYPE_07A6092B_F404_D8D8_5A51_1979ED9F5609_INCLUDED_)

#if !defined(_TC_TYPE_449C630A_94DE_C008_4CC4_4514A2E962D2_INCLUDED_)
#define _TC_TYPE_449C630A_94DE_C008_4CC4_4514A2E962D2_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_ModuleCaller
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
} ST_GetSet_E_ModuleCaller, *PST_GetSet_E_ModuleCaller;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_ModuleCaller
{
	PVOID pInst;
	TcMgSdk::ModuleCaller eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_ModuleCaller, *PST_GetSet_E_ModuleCaller;
#endif
const GUID GUID_ST_GetSet_E_ModuleCaller = {0x449C630A, 0x94DE, 0xC008, {0x4C, 0xC4, 0x45, 0x14, 0xA2, 0xE9, 0x62, 0xD2}};
#endif // !defined(_TC_TYPE_449C630A_94DE_C008_4CC4_4514A2E962D2_INCLUDED_)

#if !defined(_TC_TYPE_5CC888CB_F7E3_F010_A055_29F40ECF09F8_INCLUDED_)
#define _TC_TYPE_5CC888CB_F7E3_F010_A055_29F40ECF09F8_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_CallerVerification
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
} ST_GetSet_E_CallerVerification, *PST_GetSet_E_CallerVerification;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_CallerVerification
{
	PVOID pInst;
	TcMgSdk::CallerVerification eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_CallerVerification, *PST_GetSet_E_CallerVerification;
#endif
const GUID GUID_ST_GetSet_E_CallerVerification = {0x5CC888CB, 0xF7E3, 0xF010, {0xA0, 0x55, 0x29, 0xF4, 0x0E, 0xCF, 0x09, 0xF8}};
#endif // !defined(_TC_TYPE_5CC888CB_F7E3_F010_A055_29F40ECF09F8_INCLUDED_)

#if !defined(_TC_TYPE_318995F4_CE0A_F9BF_1620_1E7ED3D60E68_INCLUDED_)
#define _TC_TYPE_318995F4_CE0A_F9BF_1620_1E7ED3D60E68_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_StepSizeAdaptation
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
} ST_GetSet_E_StepSizeAdaptation, *PST_GetSet_E_StepSizeAdaptation;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_StepSizeAdaptation
{
	PVOID pInst;
	TcMgSdk::StepSizeAdaptation eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_StepSizeAdaptation, *PST_GetSet_E_StepSizeAdaptation;
#endif
const GUID GUID_ST_GetSet_E_StepSizeAdaptation = {0x318995F4, 0xCE0A, 0xF9BF, {0x16, 0x20, 0x1E, 0x7E, 0xD3, 0xD6, 0x0E, 0x68}};
#endif // !defined(_TC_TYPE_318995F4_CE0A_F9BF_1620_1E7ED3D60E68_INCLUDED_)

#if !defined(_TC_TYPE_8FD5CEAA_A6E7_56FF_D4AA_1D0B9DC72459_INCLUDED_)
#define _TC_TYPE_8FD5CEAA_A6E7_56FF_D4AA_1D0B9DC72459_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_ExecutionSequence1
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
} ST_GetSet_E_ExecutionSequence1, *PST_GetSet_E_ExecutionSequence1;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_ExecutionSequence1
{
	PVOID pInst;
	TcMgSdk::ExecutionSequence1 eParam;
	unsigned char reserved1[4];
} ST_GetSet_E_ExecutionSequence1, *PST_GetSet_E_ExecutionSequence1;
#endif
const GUID GUID_ST_GetSet_E_ExecutionSequence1 = {0x8FD5CEAA, 0xA6E7, 0x56FF, {0xD4, 0xAA, 0x1D, 0x0B, 0x9D, 0xC7, 0x24, 0x59}};
#endif // !defined(_TC_TYPE_8FD5CEAA_A6E7_56FF_D4AA_1D0B9DC72459_INCLUDED_)

#if !defined(_TC_TYPE_EB954E8D_311E_2175_4345_0F030823100D_INCLUDED_)
#define _TC_TYPE_EB954E8D_311E_2175_4345_0F030823100D_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_E_FpExcptCtrlSet
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[3];
} ST_GetSet_E_FpExcptCtrlSet, *PST_GetSet_E_FpExcptCtrlSet;
#elif defined(_X64_)
typedef struct _ST_GetSet_E_FpExcptCtrlSet
{
	PVOID pInst;
	TcMgSdk::FpExcptCtrlSet eParam;
	unsigned char reserved1[7];
} ST_GetSet_E_FpExcptCtrlSet, *PST_GetSet_E_FpExcptCtrlSet;
#endif
const GUID GUID_ST_GetSet_E_FpExcptCtrlSet = {0xEB954E8D, 0x311E, 0x2175, {0x43, 0x45, 0x0F, 0x03, 0x08, 0x23, 0x10, 0x0D}};
#endif // !defined(_TC_TYPE_EB954E8D_311E_2175_4345_0F030823100D_INCLUDED_)

#if !defined(_TC_TYPE_1818A80D_C7C9_0443_CB25_E525123EEC1F_INCLUDED_)
#define _TC_TYPE_1818A80D_C7C9_0443_CB25_E525123EEC1F_INCLUDED_
#if defined(_X86_)
typedef struct _ST_GetSet_ST_ModuleBuildInfo
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
} ST_GetSet_ST_ModuleBuildInfo, *PST_GetSet_ST_ModuleBuildInfo;
#elif defined(_X64_)
typedef struct _ST_GetSet_ST_ModuleBuildInfo
{
	PVOID pInst;
	TcMgSdk::ModuleBuildInfo stParam;
	unsigned char reserved1[4];
} ST_GetSet_ST_ModuleBuildInfo, *PST_GetSet_ST_ModuleBuildInfo;
#endif
const GUID GUID_ST_GetSet_ST_ModuleBuildInfo = {0x1818A80D, 0xC7C9, 0x0443, {0xCB, 0x25, 0xE5, 0x25, 0x12, 0x3E, 0xEC, 0x1F}};
#endif // !defined(_TC_TYPE_1818A80D_C7C9_0443_CB25_E525123EEC1F_INCLUDED_)

#if !defined(_TC_TYPE_ABF10CB3_B8CA_886A_7709_A7221006BE01_INCLUDED_)
#define _TC_TYPE_ABF10CB3_B8CA_886A_7709_A7221006BE01_INCLUDED_
typedef struct _ST_GetSet_ST_LibraryInfo
{
	PVOID pInst;
	TcMgSdk::LibraryInfo stParam;
} ST_GetSet_ST_LibraryInfo, *PST_GetSet_ST_LibraryInfo;
const GUID GUID_ST_GetSet_ST_LibraryInfo = {0xABF10CB3, 0xB8CA, 0x886A, {0x77, 0x09, 0xA7, 0x22, 0x10, 0x06, 0xBE, 0x01}};
#endif // !defined(_TC_TYPE_ABF10CB3_B8CA_886A_7709_A7221006BE01_INCLUDED_)

#if !defined(_TC_TYPE_7C53BC2C_3974_D48A_2D2E_448C7FC7F0D5_INCLUDED_)
#define _TC_TYPE_7C53BC2C_3974_D48A_2D2E_448C7FC7F0D5_INCLUDED_
typedef struct _ST_GetSet_ST_ModuleInfo
{
	PVOID pInst;
	TcMgSdk::ModuleInfo stParam;
} ST_GetSet_ST_ModuleInfo, *PST_GetSet_ST_ModuleInfo;
const GUID GUID_ST_GetSet_ST_ModuleInfo = {0x7C53BC2C, 0x3974, 0xD48A, {0x2D, 0x2E, 0x44, 0x8C, 0x7F, 0xC7, 0xF0, 0xD5}};
#endif // !defined(_TC_TYPE_7C53BC2C_3974_D48A_2D2E_448C7FC7F0D5_INCLUDED_)

#if !defined(_TC_TYPE_CE84954A_EAA1_7210_5F65_6B38BB802270_INCLUDED_)
#define _TC_TYPE_CE84954A_EAA1_7210_5F65_6B38BB802270_INCLUDED_
typedef struct _ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo
{
	PVOID pInst;
	TcMatSim_ModuleGeneratorInfo stParam;
} ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo, *PST_GetSet_ST_TcMatSim_ModuleGeneratorInfo;
const GUID GUID_ST_GetSet_ST_TcMatSim_ModuleGeneratorInfo = {0xCE84954A, 0xEAA1, 0x7210, {0x5F, 0x65, 0x6B, 0x38, 0xBB, 0x80, 0x22, 0x70}};
#endif // !defined(_TC_TYPE_CE84954A_EAA1_7210_5F65_6B38BB802270_INCLUDED_)

#if !defined(_TC_TYPE_297A3C44_1AAE_86EF_BF8A_0F895F27B057_INCLUDED_)
#define _TC_TYPE_297A3C44_1AAE_86EF_BF8A_0F895F27B057_INCLUDED_
typedef struct _ST_GetSet_ST_TcMatSim_SimulinkModelInfo
{
	PVOID pInst;
	TcMatSim_SimulinkModelInfo stParam;
} ST_GetSet_ST_TcMatSim_SimulinkModelInfo, *PST_GetSet_ST_TcMatSim_SimulinkModelInfo;
const GUID GUID_ST_GetSet_ST_TcMatSim_SimulinkModelInfo = {0x297A3C44, 0x1AAE, 0x86EF, {0xBF, 0x8A, 0x0F, 0x89, 0x5F, 0x27, 0xB0, 0x57}};
#endif // !defined(_TC_TYPE_297A3C44_1AAE_86EF_BF8A_0F895F27B057_INCLUDED_)

#endif // ExceptionGenerator_TYPES


#endif // _ExceptionGeneratorDuts__h_INCLUDED
