
// ****************** ExceptionGeneratorW32Resource.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.1.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.8.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorW32Resource__h_INCLUDED
#define _ExceptionGeneratorW32Resource__h_INCLUDED

//#define IDS_ModuleClass					100
#define IDR_ExceptionGeneratorCtrl			101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif // APSTUDIO_READONLY_SYMBOLS
#endif // APSTUDIO_INVOKED

#endif // _ExceptionGeneratorW32Resource__h_INCLUDED
