// ****************** ExceptionGeneratorInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.1.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.8.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorInterfaces__h_INCLUDED
#define _ExceptionGeneratorInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ExceptionGeneratorServices.h"

// interfaces provided by this driver


#if ExceptionGenerator_TYPES
#if !defined(_TC_TYPE_2806F198_B249_AEA0_AA4A_5EEEC04F9418_INCLUDED_)
#define _TC_TYPE_2806F198_B249_AEA0_AA4A_5EEEC04F9418_INCLUDED_
struct __declspec(novtable) ITcExceptionGenerator : ITcUnknown 
{
	virtual HRESULT TCOMAPI step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcExceptionGenerator, IID_ITcExceptionGenerator);
const GUID GUID_ITcExceptionGenerator = {0x2806F198, 0xB249, 0xAEA0, {0xAA, 0x4A, 0x5E, 0xEE, 0xC0, 0x4F, 0x94, 0x18}};
#endif // !defined(_TC_TYPE_2806F198_B249_AEA0_AA4A_5EEEC04F9418_INCLUDED_)

#endif // ExceptionGenerator_TYPES


#endif // _ExceptionGeneratorInterfaces__h_INCLUDED
