// ****************** TcComExceptionGenerator.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.8.1.0
// MATLAB 23.2.0.2409890 (R2023b) Update 3 (win64)
// TwinCAT 3.1.0.0
// TwinCAT Target 2.8.1.0
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _TcComExceptionGenerator__h_INCLUDED
#define _TcComExceptionGenerator__h_INCLUDED


#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcGeneratedTcCom.h"
#include "TcMatSimTcCom.h"
#include "ExceptionGeneratorInternal.h"

#include "ExceptionGeneratorInterfaces.h"
#include "ExceptionGeneratorVersion.h"


class CTcComExceptionGenerator :
	public TcMatSim::GeneratedTcCom,
	public ITcWatchSource,
	public ITcCyclic,
	public ITcPostCyclic,
	public ITcADI,
	public ITcExceptionGenerator
{
public:
	DECLARE_IUNKNOWN_DERIVED()
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_PARA()
	DECLARE_ITCADI()
	DECLARE_IPERSIST_LIB()
	DECLARE_OBJPARAASYNC()


	// Constructor
	CTcComExceptionGenerator();

	// Destructor
	~CTcComExceptionGenerator();

	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT Update(ITcTask* ipTask, ULONG_PTR context);
	TcMgSdk::ModuleInfo& GetModuleInfo();
	HRESULT CheckAndAdaptCycleTimes();

	// ITcExceptionGenerator
	HRESULT TCOMAPI step();



	ExceptionGenerator ExceptionGenerator_Obj;
	static TcMatSim_ModuleGeneratorInfo m_ModuleGeneratorInfo;
	static TcMatSim_SimulinkModelInfo m_SimulinkModelInfo;



};
			

#endif // _TcComExceptionGenerator__h_INCLUDED