// ****************** ExceptionGeneratorInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.10.0.1710957 (R2021a) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _ExceptionGeneratorInterfaces__h_INCLUDED
#define _ExceptionGeneratorInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ExceptionGeneratorServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_FBFD65D3_5B51_29F7_664A_CF48F555967E_INCLUDED_)
#define _TC_TYPE_FBFD65D3_5B51_29F7_664A_CF48F555967E_INCLUDED_
struct __declspec(novtable) ITcExceptionGenerator : ITcUnknown 
{
	virtual HRESULT TCOMAPI step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcExceptionGenerator, IID_ITcExceptionGenerator);
#endif // !defined(_TC_TYPE_FBFD65D3_5B51_29F7_664A_CF48F555967E_INCLUDED_)



#endif // _ExceptionGeneratorInterfaces__h_INCLUDED
